# Importing some Dependencies

In [1]:
import numpy as np

## Creating a Matrix Using Numpy

In [2]:
mat_1 = np.array([[2,3],[6,7]])

In [3]:
print(mat_1)

[[2 3]
 [6 7]]


In [4]:
mat_1.shape

(2, 2)

In [5]:
mat_2 = np.array([[2,3],[6,7],[4,6]])
print(mat_2)

[[2 3]
 [6 7]
 [4 6]]


In [6]:
mat_2.shape

(3, 2)

# Creating Matrices with Random Values

In [7]:
random_mat = np.random.rand(3,3) # rand gives the random numbers between 0 and 1 only
print(random_mat)

[[0.04632691 0.40924744 0.39745139]
 [0.51754496 0.70440216 0.88009577]
 [0.01713221 0.25675904 0.41898743]]


In [8]:
# Creating matrix with random Integers
rand_mat = np.random.randint(100, size=(4,5))  # randint gives the random values integer which are less than 100
print(rand_mat)

[[91 32 93 69 87]
 [90 33 11 53 13]
 [ 5 77 38 17 26]
 [74  6  6 65 29]]


## Matrix with all the elements as 1

In [9]:
mat_3 = np.ones((2,3))
print(mat_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
 mat_3 = np.ones((26,26), dtype=int) # dtype parameter defines the datatype of the values.
print(mat_3)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 

## Null or Zero Matrix

In [11]:
null_mat = np.zeros((4,4), dtype=int)
print(null_mat)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## Identity Matrix

In [12]:
ident_mat = np.eye(3,3)
print(ident_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
ident_mat = np.eye(5,6)
print(ident_mat)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


## Transpose of Matrix

In [14]:
# Matrix with Random Integer Values
a = np.random.randint(100, size=(5,5))
print(a)

[[23 51 73 32 39]
 [59 94 72 47 32]
 [99 13 60 47 52]
 [ 9 40 92 38 98]
 [34 63 69 35 96]]


In [16]:
transpose_a = np.transpose(a)
print(transpose_a)

[[23 59 99  9 34]
 [51 94 13 40 63]
 [73 72 60 92 69]
 [32 47 47 38 35]
 [39 32 52 98 96]]


# Matrix Operations

## **1. Matrix Addition**

**Two Matrices can be added only if they have the same shape.**

In [22]:
# Creating two matrices
A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)

Matrix A:
[[2 3]
 [4 5]]
Matrix B:
[[6 7]
 [8 9]]


In [26]:
A.shape

(2, 2)

In [25]:
B.shape

(2, 2)

In [27]:
# Adding the Matrix
sum = A + B
print(sum)

[[ 8 10]
 [12 14]]


In [34]:
# Taking a matrix with random values
C = np.random.randint(10,size=(3,3))
D = np.random.randint(10, size=(3,3))
print("Matrix C:")
print(C)
print("Matrix D:")
print(D)

Matrix C:
[[6 7 8]
 [1 4 3]
 [4 3 9]]
Matrix D:
[[8 8 6]
 [6 7 5]
 [8 7 7]]


In [43]:
sum = C + D
#or sum = np.add(C,D)
print(sum)

[[16 14 12]
 [11 10  3]
 [ 6 25 22]]


## **2. Matrix Subtraction**

In [37]:
# Creating two matrices
A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)

Matrix A:
[[2 3]
 [4 5]]
Matrix B:
[[6 7]
 [8 9]]


In [38]:
# Subtracting
diff = A - B
print(diff)

[[-4 -4]
 [-4 -4]]


In [40]:
# Taking a matrix with random values
C = np.random.randint(10,size=(3,3))
D = np.random.randint(20, size=(3,3))
print("Matrix C:")
print(C)
print("Matrix D:")
print(D)

Matrix C:
[[9 7 8]
 [2 3 2]
 [6 7 8]]
Matrix D:
[[ 7  7  4]
 [ 9  7  1]
 [ 0 18 14]]


In [42]:
diff = np.subtract(C,D)
print(diff)

[[  2   0   4]
 [ -7  -4   1]
 [  6 -11  -6]]


## **3. Multiplying a matrix with a Scalar**

In [44]:
x = 5
y = np.random.randint(10,size=(4,4))
print(y)

[[2 3 1 6]
 [3 4 0 8]
 [6 3 8 0]
 [5 7 9 6]]


In [45]:
product = np.multiply(x,y)
print(product)

[[10 15  5 30]
 [15 20  0 40]
 [30 15 40  0]
 [25 35 45 30]]


## **4. Multiplying 2 Matrices**

-->**The Number of column of first matrix should be equal to the number of rows to the second matrix**

In [49]:
# Taking a matrix with random values
A = np.random.randint(5,size=(2,3))
B = np.random.randint(5, size=(3,4))
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)

Matrix A:
[[1 2 0]
 [4 3 3]]
Matrix B:
[[1 2 1 1]
 [1 1 4 4]
 [0 2 1 4]]


In [50]:
product = np.dot(A,B)
print(product)

[[ 3  4  9  9]
 [ 7 17 19 28]]


In [51]:
# Taking a matrix with random values
A = np.random.randint(5,size=(2,3))
B = np.random.randint(5, size=(2,4))
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)

Matrix A:
[[4 3 4]
 [3 1 1]]
Matrix B:
[[3 3 4 0]
 [1 4 3 1]]


In [53]:
prod = np.dot(A,B)

ValueError: shapes (2,3) and (2,4) not aligned: 3 (dim 1) != 2 (dim 0)

## 5. Element Wise Multiplication

In [54]:
# Taking a matrix with random values
A = np.random.randint(5,size=(3,3))
B = np.random.randint(5, size=(3,3))
print("Matrix A:")
print(A)
print("Matrix B:")
print(B)

Matrix A:
[[4 4 1]
 [3 0 4]
 [0 4 2]]
Matrix B:
[[3 4 4]
 [4 4 3]
 [4 4 0]]


In [56]:
product = np.multiply(A,B) # multiply element to element only like scalar.
print(product)

[[12 16  4]
 [12  0 12]
 [ 0 16  0]]
