# Importing some Dependencies

In [25]:
import numpy as np

## Creating a Matrix Using Numpy

In [2]:
mat_1 = np.array([[2,3],[6,7]])

In [3]:
print(mat_1)

[[2 3]
 [6 7]]


In [4]:
mat_1.shape

(2, 2)

In [6]:
mat_2 = np.array([[2,3],[6,7],[4,6]])
print(mat_2)

[[2 3]
 [6 7]
 [4 6]]


In [7]:
mat_2.shape

(3, 2)

# Creating Matrices with Random Values

In [9]:
random_mat = np.random.rand(3,3) # rand gives the random numbers between 0 and 1 only
print(random_mat)

[[0.56736135 0.49372858 0.33362424]
 [0.25947958 0.02976411 0.53773878]
 [0.74747977 0.38194278 0.9306625 ]]


In [10]:
# Creating matrix with random Integers
rand_mat = np.random.randint(100, size=(4,5))  # randint gives the random values integer which are less than 100
print(rand_mat)

[[53 57 41 83 19]
 [17 46 21 15  4]
 [18 47 55 66 65]
 [68 83 69 92 28]]


## Matrix with all the elements as 1

In [11]:
mat_3 = np.ones((2,3))
print(mat_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
 mat_3 = np.ones((26,26), dtype=int) # dtype parameter defines the datatype of the values.
print(mat_3)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 

## Null or Zero Matrix

In [17]:
null_mat = np.zeros((4,4), dtype=int)
print(null_mat)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## Identity Matrix

In [20]:
ident_mat = np.eye(3,3)
print(ident_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
ident_mat = np.eye(5,6)
print(ident_mat)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]]


## Transpose of Matrix

In [23]:
# Matrix with Random Integer Values
a = np.random.randint(100, size=(5,5))
print(a)

[[59 36 81 98 78]
 [65 43 46 71 16]
 [21 43  6 90 32]
 [87 33 43 60 27]
 [88 71 89 22 91]]


In [24]:
transpose_a = np.transpose(a)
print(transpose_a)

[[59 65 21 87 88]
 [36 43 43 33 71]
 [81 46  6 43 89]
 [98 71 90 60 22]
 [78 16 32 27 91]]
